DECLARE @ROW VARCHAR(2000)
 SET @ROW = '[{"type":"title","children":[{"text":"Probba z plate 0009"}]},{"type":"p","children":[{"text":"hej"}]},{"type":"paragraph","children":[{"text":""}]}]'
 DECLARE @STRPOS INT

 DECLARE @TYPEENDPOS INT

 DECLARE @TYPELENGTH INT
 SET @TYPELENGTH=15
 DECLARE @TEMPTYPE VARCHAR(200)
 SELECT @STRPOS = CHARINDEX('type', @ROW)
 print @STRPOS
 WHILE @STRPOS >0
 BEGIN
 	 SET @ROW=SUBSTRING(@ROW, @STRPOS+7, len(@ROW)-@STRPOS-7+1)
	 PRINT @ROW

	 SELECT @TYPEENDPOS=CHARINDEX('"', @ROW);
SELECT @TEMPTYPE = SUBSTRING(@ROW, 0, @TYPEENDPOS)
	 PRINT @TEMPTYPE

	 SET @ROW=SUBSTRING(@ROW, @TYPEENDPOS, len(@ROW)-@TYPEENDPOS+1)
	 PRINT @ROW

	 ------INSERT @types VALUES (@TEMPTYPE);
--SET @ROW = SUBSTRING(@ROW, @STRPOS + 10, len(@ROW) - @STRPOS - 10 + 1)

     SELECT @STRPOS = CHARINDEX('type', @ROW)

	 PRINT @ROW
 END